export const columns = [
  {
    title: '机器名',
    key: 'deviceName',
    align: 'left',
    width: 170,
    ellipsis: { tooltip: true },
  },
  {
    title: '分组',
    key: 'groupName',
    align: 'left',
    width: 120,
    ellipsis: { tooltip: true },
  },
  {
    title: '主板',
    key: 'motherboard',
    align: 'left',
    minWidth: 180,
    ellipsis: { tooltip: true },
  },
  {
    title: 'BIOS版本',
    key: 'biosVersion',
    align: 'left',
    minWidth: 150,
    ellipsis: { tooltip: true },
  },
  {
    title: 'CPU',
    key: 'cpu',
    align: 'left',
    minWidth: 180,
    ellipsis: { tooltip: true },
  },
  {
    title: '内存',
    key: 'memory',
    align: 'left',
    minWidth: 180,
    ellipsis: { tooltip: true },
  },
  {
    title: '磁盘',
    key: 'disk',
    align: 'left',
    minWidth: 180,
    ellipsis: { tooltip: true },
  },
  {
    title: '显卡',
    key: 'gpu',
    align: 'left',
    minWidth: 160,
    ellipsis: { tooltip: true },
  },
  {
    title: '网卡',
    key: 'nic',
    align: 'left',
    minWidth: 180,
    ellipsis: { tooltip: true },
  },
  {
    title: '变更时间',
    key: 'changedAt',
    align: 'left',
    width: 180,
  },
];
