// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// opsDeviceDao is the data access object for the table hg_ops_device.
// You can define custom methods on it to extend its functionality as needed.
type opsDeviceDao struct {
	*internal.OpsDeviceDao
}

var (
	// OpsDevice is a globally accessible object for table hg_ops_device operations.
	OpsDevice = opsDeviceDao{internal.NewOpsDeviceDao()}
)

// Add your custom methods and functionality below.
