// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"auroraops/internal/dao/internal"
)

// opsAssetDao is the data access object for the table hg_ops_asset.
// You can define custom methods on it to extend its functionality as needed.
type opsAssetDao struct {
	*internal.OpsAssetDao
}

var (
	// OpsAsset is a globally accessible object for table hg_ops_asset operations.
	OpsAsset = opsAssetDao{internal.NewOpsAssetDao()}
)

// Add your custom methods and functionality below.
